# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yasmine Evjen | UX Designer & Product Manager
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Yasmine Evjen is a UX Designer and Product Storyteller based in Phoenix, Arizona. She can be found advocating for diversity in tech, using code and design to solve problems, and explaining to her daughter that Google isn't a real person. Hooked on mobile; you can hear her talk about it on Material Podcast, a weekly show about Google and Android on Relay FM. She was once retweeted by First Lady Michelle Obama.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: YasmineEvjen
github_username:  YasmineEvjen

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
