# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yasmine Evjen
description: > # this means to ignore newlines until "baseurl:"
  Yasmine Evjen is a Design Advocate at Google; helping designers create human-centered experiences across Google’s platforms. Proponent of pen before pixel, she uses the Google Design Sprint methodology to help teams co-create, test, and build successful products. She is the host of Centered, Google Design’s video series exploring the intersection of design, product, and people around the world.
url: "http://yasmineevjen.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: YasmineEvjen
github_username:  YasmineEvjen
linkedin_username: YasmineEvjen

# Build settings
markdown: kramdown
theme:
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
